version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: books_mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: books_db
      MYSQL_USER: books_user
      MYSQL_PASSWORD: Books123
    ports:
        - '3306:3306'
        - '33060:33060'
    volumes:
      - ./db-temp:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "books_user", "-pBooks123"]
      interval: 5s
      timeout: 20s
      retries: 10

#  books-api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - '3000:3000'
#    depends_on:
#      mysql:
#        condition: service_healthy
#    environment:
#      - DB_HOST=books_mysql
#      - DB_PORT=3306
#      - DB_USERNAME=root
#      - DB_PASSWORD="toor"
#      - DB_NAME=books_db
#      - RUN_MIGRATIONS=true
